{"location": "Rehab City، Cairo",
 "Bedrooms": 3,
 "Bathrooms": 3,
 "Area (m²)": 456,
 "Type": "Stand Alone Villa",
 "Payment Option": "Cash",
 "Compound": "not_in_Compound",
 "Delivery Term": "Finished",
 "Furnished": 0,
 "Delivery Date": "Ready to move",
 "meter_price": 16885.96,
 "Parking": 0.0,
 "Landline": 1.0,
 "Covered": 0.0,
 "A/C": 0.0,
 "Gas": 1.0,
 "Security": 1.0,
 "Natural": 1.0,
 "Water": 1.0,
 "Elevator": 0.0,
 "Pool": 0.0,
 "Pets": 1.0,
 "Kitchen": 0.0,
 "Maids": 0.0,
 "Electricity": 1.0,
 "Garden": 1.0,
 "Balcony": 1.0}